#pragma once

using namespace ATL;

template <class T>
class CProxy_IFreeRdpCtrlEvents : public IConnectionPointImpl<T, &__uuidof(_IFreeRdpCtrlEvents), CComDynamicUnkArray>
{
	// WARNING: This class may be regenerated by the wizard
public:
};
